TESTS_NUM = 22;
tests = [];
tests.push("print 4\n");
tests.push("a = 0\nprint a\n");
tests.push("a = 0\na = 5\nprint a\na = 'hgjhjg'\nprint a, 6\n");
tests.push("print 'fsdgdh' + 7\n");
tests.push("a = 5\nif a < 5:\n    print 7\n");
tests.push("a = 5\nif a < 6:\n    print 7\n");
tests.push("a = 5\nif a < 7 or a + 4 > 8:\n    print 7\nelse:\n    print 5\n");
tests.push("a = 5\nif a < 7 and a + 4 < 8:\n    print 7\nelse:\n    print 5\n");
tests.push("for cm in ['a', 'b', 'c']:\n    print cm\n");
tests.push("for i in ['a', 'b', 'c']:\n    for j in ['a', 'b', 'c']:\n        print i, j\n");
tests.push("for i in ['a', 'b', 'c']:\n    for j in ['a', 'b', 'c']:\n        if i != j:\n            print i, j\n");
tests.push("i = 0\nwhile i > 3:\n    print i\n");
tests.push("i = 0\nwhile i < 3:\n    print i\n    i += 1\n");
tests.push("i = 0\nwhile i < 3:\n    j = 0\n    while j < 2:\n        print j\n        j += 1\n    print i\n    i += 1\n");
tests.push("for i in ['a', 'b', 'c']:\n    j = 0\n    while j < 2:\n        print i, j\n        j += 1\n");
tests.push("def foo(a):\n    print a\n    \n    \nfoo(1)\n");
tests.push("def foo(a):\n    bar(a)\n    \ndef bar(a):\n    print a\n    \n    \nfoo(1)\n");
tests.push("def foo(a):\n    print bar(a)\n    \ndef bar(a):\n    return a\n    \n    \nfoo(1)\n");
tests.push("def foo(a):\n    return a\n\nprint foo(6)\n");
tests.push("def foo(a):\n    print 1\n    if a < 5:\n        return a\n    else:\n        return a - 2\n\nprint foo(6)\n");
tests.push("def rec(a):\n    print a\n    if a < 2:\n        rec(a + 1)\n    print a\n    \n    \nrec(0)\n");
tests.push("for i in range(3):\n    print i\n");
